name: build codebook pdf file

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'codebook/main.pdf'
      - 'README.md'
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build and commit
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Build PDF
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: codebook/
          root_file: 
            main.tex
          latexmk_use_xelatex: true

      - name: Commit PDF
        uses: actions/upload-artifact@v3
        with:
          name: codebook.pdf
          path: codebook/main.pdf